'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BSITCapstone.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to xXOcAQCK0lzZkLVnvECLooo2PzvnmaVZkBuk+a4s65GYtLkOtECrGK7BL5XEQ80NXwgfPuKRhg5iKLNJhDDI1eqJk+mrcIjpXa0sAEw0pKItMvXvzsgA9dc5UwHVlowe7QEl1HR1XWSu/CxGUqiSlJEsTJNh1l7MqHJeIFNBuGK/oBF3UEO8YumsSfGXgqXRLPteCyIdztL5n5qEEmkwI6psIgC/awi3I4nDL7kQEt6edzCMyjIVBL41y1uqBizbj8FNtc6dCBemCWNDVr5QRL/lRZJyEsN3G0Pkm47gCrrD4A9CTFIlURSlpTrhN99z16JXzYVUZUgwFUi0A8XEJ21f8h6Bts0aLzdaJQ6VDQiLdj3Wy7HTSIcJ216+dhIuCq31JUK64IuEARzeUtTRI4Y7eT9mo6A1dppVWxZoms4a9R7XkNBPWb/8QI1HzU/zPzGV2yoU5JTruRB7BQ2UCu1Vqv3oQu+iBGvJ9PlXACbsrAdndMPpLLXLt8oQ07iX [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property strKey() As String
            Get
                Return ResourceManager.GetString("strKey", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
